// AUTH ACTIONS
export const SIGNUP_SUCCEED = 'SIGNUP_SUCCEED';
export const SESSION_VALID = 'SESSION_VALID';

// TENANT ACTIONS
export const DEFAULT_TENANT = 'DEFAULT_TENANT';
export const ADD_NEW_NOTIFICATION_FAIL = 'ADD_NEW_NOTIFICATION_FAIL';

//send mail
export const SEND_EMAIL = 'SEND_EMAIL';
export const MEASUREMENTS = 'MEASUREMENTS'; //get measurements

export const GET_USER = 'GET_USER'; //get user
export const GET_WEBTOKEN = 'GET_WEBTOKEN';
export const GET_SESSION_USER_PARTICIPANT = 'GET_SESSION_USER_PARTICIPANT';
export const PARTICIPANT_VALID = 'PARTICIPANT_VALID';
export const USER_DEVICE = 'USER_DEVICE';
export const GET_SESSION_PARTICIPANT_EMAIL = 'GET_SESSION_PARTICIPANT_EMAIL';
export const UPDATE_SEND_EMAIL = 'UPDATE_SEND_EMAIL';
export const EMAIL_RESPONSE = "EMAIL_RESPONSE";
export const UPDATE_TRACK_STATUS = "UPDATE_TRACK_STATUS";